
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: networktraffics.metal-stack.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.nodeexporterurl
    name: NodeExporter
    type: string
  - JSONPath: .spec.enabled
    name: Enabled
    type: boolean
  - JSONPath: .spec.interval
    name: Interval
    type: string
  - JSONPath: .spec.interfaces
    name: Interfaces
    type: string
  group: metal-stack.io
  names:
    kind: NetworkTraffic
    listKind: NetworkTrafficList
    plural: networktraffics
    singular: networktraffic
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NetworkTraffic is the Schema for the networks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NetworkTrafficSpec defines the desired state of Network
          properties:
            enabled:
              description: Enabled if set to true networktraffic is collected and
                reported.
              type: boolean
            interfaces:
              description: Interfaces is a glob pattern which defines from which interfaces
                network traffic should be collected.
              type: string
            interval:
              description: Intervall at which networktraffic should be accounted,
                go duration format allowed.
              type: string
            localprefixes:
              description: LocalPrefixes specify prefixes which are considered local
                to the partition or all regions. Traffix to/from these prefixes is
                not accounted
              items:
                type: string
              type: array
            nftablesexporterurl:
              description: NFTablesExportURL is the url where the nftables exporter
                exposes the metrics.
              type: string
          type: object
        status:
          description: NetworkTrafficStatus defines the observed state of Network
          properties:
            devicestatistics:
              description: DeviceStatistics is a list of statistics of all devices
              properties:
                items:
                  items:
                    description: DeviceStatistic contains statistics of a device
                    properties:
                      device:
                        type: string
                      in:
                        format: int64
                        type: integer
                      out:
                        format: int64
                        type: integer
                    required:
                    - device
                    - in
                    - out
                    type: object
                  type: array
              required:
              - items
              type: object
            lastRun:
              format: date-time
              type: string
          required:
          - devicestatistics
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
